# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

def pods_files
    pod 'Masonry'
    pod 'XBImageManager'
end

target 'XBBannerViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pods_files
  # Pods for XBBannerViewDemo

  target 'XBBannerViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XBBannerViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
